- repo: https://github.com/antonbabenko/pre-commit-terraform
  sha: v1.11.0
  hooks:
    - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v2.2.1
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: check-added-large-files
    - id: detect-private-key
